package graphics;

import game.Client;
import javafx.event.ActionEvent;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.shape.Ellipse;
import network.Instruction;

/**
 * FXML controller for file waiting.fxml. Extends OverlordCtrl and implements CtrlNecessities
 */
public class WaitingCtrl extends OverlordCtrl implements CtrlNecessities {
    // Status bar elements
    public Ellipse clientConnectCircle;
    public Label responseLabel;
    public Label clientStateLabel;
    public Label clientNameLabel;
    public Label clientConnectionLabel;
    public Ellipse opponentConnectCircle;
    public Label opponentConnectionLabel;
    public Label opponentNameLabel;

    /** Cancel Button */
    public Button cancelWaitBtn;

    /**
     * Ref. to @CtrlNecessities
     * @param client instance
     */
    public void setClient(Client client) {
        StatusBar status = new StatusBar(clientConnectCircle, responseLabel, clientStateLabel, clientNameLabel,
                clientConnectionLabel, opponentConnectCircle, opponentConnectionLabel, opponentNameLabel);
        setClient(client, status);
    }

    /**
     * Sets instruction to DELETE_LOBBY and cancels wait on server OK response
     * @param actionEvent autogenerated, isn't used
     */
    public void cancel(ActionEvent actionEvent) {
        client.setInstruction(Instruction.DELETE_LOBBY);
    }
}
