SELECT  
	s.NOVE_PRIJATY AS STD_NOVE_PRIJATY,
	s.STUPEN_PRED_VZDELANI AS STD_STUPEN_PRED_VZDELANI,
	s.POCET_ZAPISOVYCH_PROPUSTEK AS STD_POCET_PROPUSTEK,
	sp.FORMA AS SP_FORMA,
	sp.FAKULTA_SP AS SP_FAKULTA_PROGRAMU,
	svr.ROK_PLATNOSTI AS SVR_ROK,
	z.POC_KRED AS ZN_KREDITY_ZA_PREDMET,
	z.STATUT AS ZN_STATUT_PREDMETU,
	z.POKUS_CISLO AS ZN_POKUS_CISLO,
	z.HODNIDNO_ZKZP AS ZN_HODNOCENI,
	z.TYP_ZK AS ZN_TYP_ZKOUSKY,
	z.PRAC_ZKR AS ZN_PRACOVISTE_ZKRATKA,
	z.ZAPOCET_POKUS AS ZN_ZAPOCET_POKUS,
	CASE
        WHEN aa.OS_CISLO IS NOT NULL 
        THEN '1' || sp.FORMA
        ELSE '0' || sp.FORMA
    END AS CLASS
FROM STUDENTI s
	INNER JOIN STUDENTI_V_ROCE svr 
		ON s.OS_CISLO = svr.OS_CISLO
	INNER JOIN STUDIJNI_PROGRAMY sp 
		ON s.STPRIDNO = sp.STPRIDNO
	INNER JOIN ZNAMKY z
		ON z.OS_CISLO = svr.OS_CISLO 
		AND z.ROK_PLATNOSTI = svr.ROK_PLATNOSTI
	INNER JOIN CIS_HODNOCENI ch
		ON ch.HODNIDNO = z.HODNIDNO_ZKZP
	LEFT JOIN ABN_ABSOLVENTI aa 
		ON s.OS_CISLO = aa.OS_CISLO 
WHERE
	svr.PRERUS_LS = 'N' 
	AND svr.PRERUS_ZS = 'N'
	AND s.DAT_UKONCENI IS NOT NULL
	AND z.TYHOIDNO_ZKZP = 1  -- ONLY SELECT grades WITH exams
	AND z.STATUT != '8'
--	AND ROWNUM <= 50000 AND z.DATE_OF_INSERT < TO_DATE('2015-10-02 00:00:00', 'yyyy-MM-dd hh24:mi:ss') -- USING DATE FILTER, because there ARE NO NEW distant student AFTER 2015
ORDER BY z.DATE_OF_INSERT DESC